sequenceDiagram
    participant StartMachine
    participant Machine
    participant FuelTank
    participant Engine

    StartMachine->>Machine: Machine()
    Machine->>FuelTank: FuelTank()
    Machine->>FuelTank: FuelTank.fill(40)
    Machine->>Engine: Engine(self.tank)

    StartMachine->>Machine: Machine.drive()
    Machine->>Engine: Engine.start()
    Engine->>FuelTank: FuelTank.consume(5)
    StartMachine->>Engine: Engine.is_running()

    Engine->>FuelTank: check: FuelTank.fuel_contest > 0
    Note over FuelTank: FuelTank.fuel_contents = 35
    StartMachine->>Engine: Engine.use_energy()
    Engine->>FuelTank: FuelTank.consume(10)
    Note over FuelTank: FuelTank.fuel_contents = 25
